name: Build

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    #mimic "skip_branch_with_pr: true", see https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012/4
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        os: [ windows-2019, ubuntu-18.04, macos-10.15 ]

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow

      - uses: actions/setup-dotnet@v1.9.0
        with:
          # codecov and unittests need 2.1
          dotnet-version: '2.1.818'
      - uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '3.1.414'
      - uses: actions/setup-dotnet@v1.9.0
        with:
          # gitversion needs 5.0
          dotnet-version: '5.0.402'
      - uses: actions/setup-dotnet@v1.9.0
        with:
          # need at least .NET 6 rc2 to build
          dotnet-version: '6.0.100-rc.2.21505.57'
          include-prerelease: true

      - name: Cache Tools
        uses: actions/cache@v2
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}

      - name: Build project
        uses: cake-build/cake-action@v1
        with:
          script-path: recipe.cake
          target: CI
          verbosity: Verbose
          cake-version: 0.38.5
          cake-bootstrap: true

      # currently, Cake.Recipe does not upload artifacts when run on gh-actions
      - name: Upload Issues
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: warn
          name: ${{ matrix.os }} Issues
          path: |
            BuildArtifacts/report.html
            BuildArtifacts/**/coverlet/*.xml

      - name: Upload Packages
        uses: actions/upload-artifact@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          if-no-files-found: warn
          name: package
          path: BuildArtifacts/Packages/**/*
